### PR TITLE
[INT-931] Docs about new PluginMethod (Exporter.createAutoExport)

### PR DESCRIPTION
**Pull request by agataHappy**
**Ticket**
https://dronedeploy.atlassian.net/browse/INT-931

**Work done**
Added new plugin method of Exporter to docs with example of usage.

**Screenshots**

**Example**: 
Zrzut ekranu z 2019-06-07 09-46-56

**Example response in console**
Zrzut ekranu z 2019-06-07 09-50-54

**Exporter file**
Zrzut ekranu z 2019-06-07 09-54-28

### CODE REVIEW

**Comment by mikolaj-leszczynski** [comment]
@agataHappy please give us some screens :)

**Comment by mikolaj-leszczynski** [comment]
@agataHappy why is the button named `Export` ?

**Comment by agataHappy** [comment]
@mikolaj-leszczynski No specific reason, thought it describe what we're doing, i.e. exporting

**Review by mikolaj-leszczynski — APPROVED** [review]
LGTM

**Pull request merged**
